[versions]
kotlin = "1.8.0"

gradle-versions = "0.44.0"

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }

gradle-versions = { id = "com.github.ben-manes.versions", version.ref = "gradle-versions" }
