name: Publish snapshot
on: [ workflow_call, workflow_dispatch ]

env:
  ORG_GRADLE_PROJECT_signingKey: ${{secrets.signingKey}}
  ORG_GRADLE_PROJECT_signingPassword: ${{secrets.signingPassword}}
  ORG_GRADLE_PROJECT_sonatypeUsername: ${{secrets.sonatypeUsername}}
  ORG_GRADLE_PROJECT_sonatypePassword: ${{secrets.sonatypePassword}}

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "KONAN_DATA_DIR=${HOME}/.gradle/konan" >> $GITHUB_ENV

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Publish to Maven Local (prepare packages)
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishToMavenLocal --scan --info
          cache-disabled: true
      - name: Publish snapshot to Sonatype
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishAllPublicationsToSnapshotRepository --scan --info
          cache-disabled: true
