name: Run tests on all platforms
on: [ workflow_call, workflow_dispatch ]

jobs:
  test:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
    steps:
      - uses: actions/checkout@v3
      - if: matrix.os != 'windows-latest'
        run: echo "KONAN_DATA_DIR=${HOME}/.gradle/konan" >> $GITHUB_ENV
      - if: matrix.os == 'windows-latest'
        run: echo "KONAN_DATA_DIR=${USERPROFILE}\.gradle\konan" >> $GITHUB_ENV
        shell: bash

      - if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          release: false
          update: true
          install: mingw-w64-x86_64-openssl

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: |
            8
            19

      - name: Run tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check --scan --continue
          cache-disabled: true
      - name: Publish to Maven Local
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishToMavenLocal --scan --continue
          cache-disabled: true
